name: ebroker #! DO NOT CHANGE THIS
description: Welcome to eBroker.

publish_to: 'none'

version: 1.2.1+52

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.0
  #Firebase
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  #  firebase_analytics: ^11.1.0
  #  firebase_core_platform_interface: 5.0.0

  #Signin
  sign_in_with_apple: ^6.1.3
  google_sign_in: ^6.2.1

  #visuals
  panorama: ^0.4.1
  video_player: ^2.9.2

  youtube_player_flutter: ^9.1.1


  flick_video_player: ^0.9.0

  #Network
  http: any
  dio: ^5.7.0

  #Pickers
  country_picker: ^2.0.26
  sms_autofill: ^2.4.0
  image_picker: ^1.1.2

  #Animations
  shimmer: ^3.0.0
  lottie: ^3.1.2

  #Network
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0

  #image rendering
  #  octo_image: ^2.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  flutter_native_image: 0.0.6+1
  #  TODO(R): use this if flutter_native_image is not working
  #  flutter_image_compress: ^2.3.0
  dotted_border: ^2.1.0
  flutter_html: ^3.0.0-beta.1
  share_plus: ^10.0.3
  launch_review: ^3.0.1
  #payment gateways
  razorpay_flutter: ^1.3.7
  in_app_purchase: ^3.2.0
  flutter_stripe: ^11.2.0
  flutter_sim_country_code: ^0.1.2
  google_maps_flutter: 2.2.1
  awesome_notifications: 0.10.0
  device_preview: ^1.2.0
  path_provider: ^2.1.4
  record: ^5.2.0
  audioplayers: ^6.1.0
  image_cropper: any
  permission_handler: ^11.3.1
  open_filex: ^4.6.0
  package_info_plus: ^8.0.3
  fluttertoast: ^8.2.8
  #  hydrated_bloc: ^9.1.5
  label_marker: ^1.0.1
  flutter_typeahead: ^5.2.0
  geocoding: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  latlong2: ^0.9.1
  encrypt: ^5.0.3
  google_mobile_ads: ^5.2.0
  #  uni_links: ^0.5.1
  change_app_package_name: ^1.4.0
  youtube_explode_dart: any
  device_info_plus: ^11.0.0
  json_view: ^0.4.2
  geolocator: ^13.0.1
  timeago: ^3.7.0
  app_links: ^6.3.2
  flutter_sound: ^9.17.0
  http_parser: any
  flutterwave: ^1.0.3
  file_picker: 8.1.2


dependency_overrides:
  http: ^0.13.5 #TODO UPDATE PACKAGE
  flutter_paystack:
    git:
      url: https://github.com/I-driod/flutter_paystack.git
      ref: master
  google_maps_flutter_ios: ^2.13.2
  #  webview_flutter_android: ^4.0.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  intl: ^0.19.0
  js:

  flutter_launcher_icons: ^0.14.1

  motion_sensors:
    git:
      url: https://github.com/zesage/motion_sensors
      ref: master


  # file_version_info: any


dev_dependencies:
  rename: ^3.0.2


  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
#  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #  - assets/image/
    - assets/svg/
    - assets/AppIcon/
    - assets/languages/
    - assets/lottie/
    - assets/chat_background/
    - assets/svg/MultiColorSvg/
    - assets/svg/Logo/
    - assets/svg/Fallback/
    - assets/city.jpg
    - assets/map.png
    - assets/location_rent.png
    - assets/location_sell.png
    - assets/location_selected.png
    - assets/login_background.png

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800


